<?php

namespace mmerlijn\msgEdifact\tests\Unit\segments;

use mmerlijn\msgEdifact\Edifact;
use mmerlijn\msgRepo\Msg;
use mmerlijn\msgRepo\Phone;

class AFDTest extends \mmerlijn\msgEdifact\tests\TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->edifact = new Edifact("AFD+BIG COMP+0031-11223344'");

    }

    public function test_department_setter()
    {
        $msg = new Msg();
        $edifact = new Edifact();

        $msg->sender->setOrganisation(['name' => "Syntc BV"]);
        $msg->sender->setPhone("0123456789");
        $edifact->setMsg($msg);
        $this->assertStringContainsString("AFD+Syntc BV+012 3456 789'", $edifact->write());
    }

    public function test_department_getter()
    {
        $msg = $this->edifact->getMsg(new Msg());
        $array = $msg->toArray();
        $this->assertSame("BIG COMP", $msg->sender->organisation->name);
        $this->assertSame("011 2233 44", (string)$msg->sender->organisation->phone);

    }

    public function test_validator()
    {
        $this->expectException(\Exception::class);
        $this->expectExceptionMessageMatches('/sender_organisation_name/');
        $edifact = (new Edifact())->setMsg(new Msg());
        $edifact->write(true);
    }
}