<?php

namespace mmerlijn\msgEdifact\tests\Unit\segments;

use mmerlijn\msgEdifact\Edifact;
use mmerlijn\msgEdifact\tests\TestCase;
use mmerlijn\msgRepo\Msg;
use mmerlijn\msgRepo\OrderItem;
use mmerlijn\msgRepo\Result;

class NUBTest extends TestCase
{
    public $edifact;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->edifact = new Edifact("NUB:1:1+ABC'");
    }

    public function test_order_getter()
    {
        $msg = $this->edifact->getMsg(new Msg());
        $array = $msg->toArray();
        $this->assertSame('ABC', $msg->order->results[0]->test_name);
    }

    public function test_order_setter()
    {
        $msg = new Msg();
        $msg->order->addResult(new Result(done: true, test_name: "QQT",test_code: "QQT",));
        $msg->order->addResult(new Result(done: false, test_name: "BCA",test_code: "BCA"));
        $msg->order->addResult(new Result(done: false, test_name: "ABC",test_code: "ABC"));
        $edifact = (new Edifact())->setMsg($msg);
        $edifact->write();
        $this->assertStringContainsString("NUB:1:1+BCA", $edifact->write());
        $this->assertStringContainsString("NUB:1:2+ABC", $edifact->write());
        $this->assertStringContainsString("BEP:1:1:1+0+QQT", $edifact->write());
    }
}