<?php

namespace mmerlijn\msgEdifact\tests\Unit\segments;

use mmerlijn\msgEdifact\Edifact;
use mmerlijn\msgEdifact\tests\TestCase;
use mmerlijn\msgRepo\Msg;
use mmerlijn\msgRepo\OrderItem;

class TXTTest extends TestCase
{
    public $edifact;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->edifact = new Edifact("PAD+Straat:16::Amsterdam:1000AA+0612341234'
TXT:1+Do the things you love'
TXT:2+Today or tomorrow'");
    }

    public function test_order_and_comment_getter()
    {
        $msg = $this->edifact->getMsg(new Msg());
        $this->assertSame('Do the things you love', $msg->comments[0]);
        $this->assertSame('Today or tomorrow', $msg->comments[1]);
    }

    public function test_order_and_comment_setter()
    {
        $msg = new Msg();
        $msg->msgType->type = "MEDVRI";
        $msg->addComment("Hello World!");
        $file = (new Edifact())->setMsg($msg)->write();
        $this->assertStringContainsString("TXT:1+Hello World!", $file);
        $this->assertStringContainsString("GGA", $file); //only for medvri
        $this->assertStringContainsString("GGO", $file);

    }
}