<?php

namespace mmerlijn\msgEdifact\tests\Unit\segments;

use mmerlijn\msgEdifact\Edifact;
use mmerlijn\msgRepo\Msg;
use mmerlijn\msgRepo\Phone;

class UNTTest extends \mmerlijn\msgEdifact\tests\TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->edifact = new Edifact("UNT+16+123123123'");

    }

    public function test_segment_setter()
    {
        $msg = new Msg();
        $edifact = new Edifact();

        $msg->id = "11223344";
        $edifact->setMsg($msg);
        $aantal = count($edifact->segments) - 2; //first and last do not count
        $this->assertStringContainsString("UNT+" . $aantal . "+11223344'", $edifact->write());
    }
    //nothing to test
    //public function test_segment_getter()
    //{
    //}

    public function test_validator()
    {
        $this->expectException(\Exception::class);
        $this->expectExceptionMessageMatches('/message_id required failure/');
        $edifact = (new Edifact())->setMsg(new Msg());
        $edifact->write(true);
    }
}