<?php

namespace mmerlijn\msgEdifact\tests\Unit\segments;

use mmerlijn\msgEdifact\Edifact;
use mmerlijn\msgRepo\Msg;

class UNZTest extends \mmerlijn\msgEdifact\tests\TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->edifact = new Edifact("UNZ+1+AB123123123'");

    }

    public function test_segment_setter()
    {
        $msg = new Msg();
        $edifact = new Edifact();

        $msg->processing_id = "AB123123123";
        $edifact->setMsg($msg);
        $this->assertStringContainsString('UNZ+1+AB123123123', $edifact->write());
    }

    public function test_validation()
    {
        $this->expectException(\Exception::class);
        $this->expectExceptionMessageMatches('/processing_id required failure/');
        $edifact = (new Edifact())->setMsg(new Msg());
        $edifact->write(true);

    }
}